version: "3"
services:

  traefik:
    image: traefik:latest
    ports:
      - 443:443
      - 80:80
    #dashboard
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/ssl/:/ssl-certs/
    networks:
      - traefik

networks:
  traefik:
    external: true