version: '3'
services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0
    environment:
      - PUID=1000
      - PGID=1000

    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
      - SYS_ADMIN
    privileged: true
    networks:
      - traefik
#    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ha.entrypoints=web, websecure"
      - "traefik.http.routers.ha.rule=Host(`foo.bar`)"
      - "traefik.http.routers.ha.tls=true"
      - "traefik.http.routers.ha.tls.certresolver=production"
      - "traefik.http.services.ha.loadbalancer.server.port=8123"
networks:
  traefik:
    external: true
