http:
  use_x_forwarded_for: true
  trusted_proxies:
    - <add your docker IP subnet here with /24>

binary_sensor:
  - platform: ffmpeg_motion
    name: Set_Name_Here
    input: -rtsp_transport tcp -i rtsp://admin:<password@<ip address>:554/live/profile.0/video

#camera:
#  - platform: ffmpeg
#    name: Set_Name_Here
#    input: -rtsp_transport tcp -i rtsp://admin:<password@<ip address>:554/live/profile.0/video




# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
