version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
#    user: uid:gid
#    network_mode: 'host'

#  Remove the 2 comments below to expose the jellyfin container ports to your host computer, to be able to reach it from http://localhost:8096
#    ports:
#      - 8096:8096

    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.foo.bar
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=web, websecure"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.foo.bar`)"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=production"
#      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
networks:
  traefik:
    external: true
