version: "3"
services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:nightly
    restart: always
    networks:
      - traefik
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=<set baseURL here>
    labels:
    #  - "traefik.http.middlewares.auth.basicauth.users=<user>:<password>
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.entrypoints=web, websecure"
      - "traefik.http.routers.mealie.rule=Host(`<set domain address here>`)"
      - "traefik.http.routers.mealie.tls=true"
      - "traefik.http.routers.mealie.tls.certresolver=production"
    #  - "traefik.http.routers.mealie.middlewares=auth" # Link the auth middleware here
networks:
  traefik:
    external: true
volumes:
  mealie-data:
    driver: local
