version: "3"
services:
  nginx:
    image: nginx
    networks:
      - "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
networks:
  traefik:
    external: true