version: "3.7"
services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - traefik
    #the first example escapes the generated password, and add another $ since that is according to the documentation needed...   
    # echo $(htpasswd -nb my_user my_password) | sed -e s/\\$/\\$\\$/g
    labels:
      - "traefik.http.middlewares.auth.basicauth.users=my_user:my_password"
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.entrypoints=web, websecure"
      - "traefik.http.routers.nodered.rule=Host(`nodered.zaeta.se`)"
      - "traefik.http.routers.nodered.tls=true"
      - "traefik.http.routers.nodered.tls.certresolver=staging"
      - "traefik.http.routers.nodered.middlewares=auth" # Link the auth middleware here
      
networks:
  traefik:
    external: true

