version: "3.7"
services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.rule=Host(`nodered.localhost`)"
      - "traefik.http.services.nodered.loadbalancer.server.port=1880"
networks:
  traefik:
    external: true