version: "3.7"
services:
  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodered.entrypoints=web, websecure"
      - "traefik.http.routers.nodered.rule=Host(`nodered.localhost`)"
      - "traefik.http.routers.nodered.tls=true"
      - "traefik.http.routers.nodered.tls.certresolver=staging"
networks:
  traefik:
    external: true