global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
       entryPoint:
         to: websecure
         scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: default

certificatesResolvers:
  default:
    acme:
      email: email@foo.bar
      storage: /ssl-certs/acme.json
      httpChallenge:
        entryPoint: web

  staging:
      acme:
        email: email@foo.bar
        storage: /ssl-certs/acme.json
        httpChallenge:
          entryPoint: web
        caServer: https://acme-staging-v02.api.letsencrypt.org/directory  

providers:
  docker:
     exposedByDefault: false